# Edit database name, username, password, and host/port below to match your PostgreSQL setup
spring:
  application:
    name: inbound-receiving-service
  datasource:
    url: jdbc:postgresql://localhost:5432/inbound_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 161717
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8090
