spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cms_db
    username: cms_user
    password: cms_pass

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace   # show SQL bind params (Hibernate 6)