spring:
  application:
    name: customer-management-service

  datasource:
    url: jdbc:postgresql://localhost:5432/cms_db
    username: cms_user
    password: cms_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate            # rely on Flyway for schema
    properties:
      hibernate:
        format_sql: true
    open-in-view: false             # recommended for REST APIs

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always        # or when_authorized (if you add security)
      show-components: always     # show component names like "db"
      probes:
        enabled: true             # optional, for liveness/readiness